[package]
name = "time"
version = "0.1.2"
edition = "2021"
publish = false

[target.'cfg(target_family="windows")'.dependencies.winapi]
version = "0.3"
features = ["timezoneapi","impl-default","impl-debug","errhandlingapi"]